export default [
    "TypeScript",
    "JavaScript",
    "Python",
    "SQLite",
    "MongoDB",
    "PostgreSQL",
    "HTML",
    "CSS",
    "SASS",
    "SCSS",
    "EJS",
    "Jinja2",
    "Node.js",
    "VSCode",
    "NeoVim",
    "Figma",
    "Git & GitHub",
    "FontAwesome",
    "XFCE",
    "React",
    "Vue",
    "Disnake",
    "Discord.js",
    "Flask & Quart",
    "Express"
]